GestionReservationAuto/Entity/Registre.php
<?php

namespace DTC\Modules\GestionReservationAuto\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Reservation
 * @ORM\Entity(repositoryClass="DTC\Modules\GestionReservationAuto\Repository\RegistreRepository")
 * @ORM\Table(name="T_REGISTRE_REG")
 */
class Registre
{
    /**
     * @var integer
     *
     * @ORM\Column(name="REG_ID", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $idRegistre;
    
    /**
     * @ORM\ManyToOne(targetEntity="DTC\Modules\GestionReservationAuto\Entity\User")
     * @ORM\JoinColumns({
     *  @ORM\JoinColumn(name="REG_USER", referencedColumnName="USE_ID")
     * })
     */
    private $user;
    
    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="REG_DATE_DEBUT", type="datetime")
     */
    private $dateDebut;
    
    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="REG_DATE_FIN", type="datetime")
     */
    private $dateFin;
    
    /**
     * @var \DateTime
     * 
     * @ORM\Column(name="REG_DATE_CREATION", type="datetime")
     */
    private $dateCreation;
    /**
     * @var string
     * 
     * @ORM\Column(name="REG_SIGNATURE_AGENT", type="string")
     */
    private $signatureAgent;
    /**
     * @var string
     * 
     * @ORM\Column(name="REG_SIGNATURE_SUPERIEUR", type="string")
     */
    private $signatureSuperieur;
    
    /**
     * Get idReservation
     *
     * @return integer 
     */
    public function getIdRegistre()
    {
        return $this->idRegistre;
    }
    /**
     * Set User
     *
     * @param string $user
     * @return Reservation
     */
    public function setUser($user)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get User
     *
     * @return User 
     */
    public function getUser()
    {
        return $this->user;
    }
    
    /**
     * Set dateDebut
     *
     * @param string $dateDebut
     * @return Reservation
     */
    public function setDateDebut($dateDebut)
    {
        $this->dateDebut = $dateDebut;

        return $this;
    }

    /**
     * Get dateDebut
     *
     * @return datetime 
     */
    public function getDateDebut()
    {
        return $this->dateDebut;
    }
    
    /**
     * Set dateFin
     *
     * @param string $dateFin
     * @return Reservation
     */
    public function setDateFin($dateFin)
    {
        $this->dateFin = $dateFin;

        return $this;
    }

    /**
     * Get dateFin
     *
     * @return dateFin 
     */
    public function getDateFin()
    {
        return $this->dateFin;
    }
    
    /**
     * Set dateCreation
     *
     * @param string $dateCreation
     * @return Reservation
     */
    public function setDateCreation($dateCreation)
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    /**
     * Get dateCreation
     *
     * @return dateCreation 
     */
    public function getDateCreation()
    {
        return $this->dateCreation;
    }
    /**
     * Set destination
     *
     * @param string $destination
     * @return Reservation
     */
    public function setDistination($destination)
    {
        $this->destination = $destination;

        return $this;
    }
    
    /**
     * Set signatureAgent
     *
     * @param string $signatureAgent
     * @return Reservation
     */
    public function setSignatureAgent($signatureAgent)
    {
        $this->signatureAgent = $signatureAgent;

        return $this;
    }

    /**
     * Get signatureAgent
     *
     * @return signatureAgent 
     */
    public function getSignatureAgent()
    {
        return $this->signatureAgent;
    }
    
    /**
     * Set signatureSuperieur
     *
     * @param string $signatureSuperieur
     * @return Reservation
     */
    public function setSignatureSuperieur($signatureSuperieur)
    {
        $this->signatureSuperieur = $signatureSuperieur;

        return $this;
    }

    /**
     * Get signatureSuperieur
     *
     * @return signatureSuperieur 
     */
    public function getSignatureSuperieur()
    {
        return $this->signatureSuperieur;
    }
}

GestionReservationAuto/Entity/User.php
<?php

namespace DTC\Modules\GestionReservationAuto\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass="DTC\Modules\GestionReservationAuto\Repository\UserRepository")
 * @ORM\Table(name="T_USER_USE")
 * @Gedmo\SoftDeleteable(fieldName="deletedAt", timeAware=false)
 */
class User extends \DTC\Common\Entity\Master\AbstractEntity
{

    public function __construct()
    {
        $this->reservations = new \Doctrine\Common\Collections\ArrayCollection();
        $this->registres = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * @ORM\Id
     * @ORM\Column(name="USE_ID", type="string")
     */
    private $idUser;

    /**
     * @ORM\Column(name="USE_ADRESSE", type="string")
     */
    private $adresse;

    /**
     * @ORM\Column(name="USE_CP", type="string")
     */
    private $cp;

    /**
     * @ORM\Column(name="USE_VILLE", type="string")
     */
    private $ville;

    /**
     * @ORM\Column(name="USE_TELEPHONE", type="string")
     */
    private $telephone;

    /**
     * @ORM\Column(name="USE_GRADE", type="string")
     */
    private $grade;

    /**
     * @ORM\OneToOne(targetEntity="\DTC\Modules\GestionReservationAuto\Entity\Perimetre")
     * @ORM\JoinColumn(name="USE_PER_ID", referencedColumnName="PER_ID")
     */
    private $perimetre;

    /**
     * @ORM\Column(name="USE_MAIL_SUPERIEUR", type="string")
     */
    private $mailSuperieur;

    /**
     * @ORM\OneToOne(targetEntity="\DTC\Modules\GestionReservationAuto\Entity\Voiture")
     * @ORM\JoinColumn(name="USE_VOITURE_ATTRIBUE", referencedColumnName="VOI_ID")
     */
    private $voitureAttribue;

    /**
     * @ORM\Column(name="USE_DISTANCE_TRAVAIL_DOMICILE", type="string")
     */
    private $distanceDT;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="USE_CREATE_AT", type="datetime")
     */
    private $createAt;

    /**
     * @Gedmo\Blameable(on="create")
     * @ORM\Column(name="USE_CREATE_BY", type="string")
     */
    private $createBy;

    /**
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(name="USE_UPDATE_AT", type="datetime")
     */
    private $updateAt;

    /**
     * @Gedmo\Blameable(on="update")
     * @ORM\Column(name="USE_UPDATE_BY", type="string")
     */
    private $updateBy;

    /**
     * @ORM\Column(name="USE_DELETE_AT", type="datetime", nullable=true)
     */
    private $deletedAt;

    /**
     * @ORM\OneToOne(targetEntity="\DTC\Modules\GestionReservationAuto\Entity\GestionRh\SourceAgent", inversedBy="gpaUser", fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="USE_AGE_CODE_DT", referencedColumnName="AGE_CODE_DT")
     * @var \DTC\Modules\GestionReservationAuto\Entity\GestionRh\SourceAgent
     * */
    private $sourceAgent;

    function getHierarchique()
    {
        return $this->sourceAgent->getResponsableHierarchique();
    }

    function getHierarchiqueNomComplet()
    {
        return $this->getHierarchique()->getFullName();
    }

    function getHierarchiqueMail()
    {
        return $this->getHierarchique()->getCtcMessagerie();
    }

    /**
     * @ORM\OneToMany(targetEntity="\DTC\Modules\GestionReservationAuto\Entity\Reservation", mappedBy="user", cascade={"remove"})
     * */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity="\DTC\Modules\GestionReservationAuto\Entity\Registre", mappedBy="user", cascade={"remove"})
     * */
    private $registres;

    /**
     * Alias of SourceAgent.agePrenomUsuel
     * @return string
     */
    public function getPrenom()
    {
        return $this->sourceAgent->getAgePrenomUsuel();
    }

    /**
     * Alias of SourceAgent.ageNomUsuel
     * @return string
     */
    public function getNom()
    {
        return $this->sourceAgent->getAgeNomUsuel();
    }

    public function getIdUser()
    {
        return $this->idUser;
    }

    public function getAdresse()
    {
        return $this->adresse;
    }

    public function getCp()
    {
        return $this->cp;
    }

    public function getVille()
    {
        return $this->ville;
    }

    public function getTelephone()
    {
        return $this->telephone;
    }

    public function getGrade()
    {
        return $this->grade;
    }

    public function getMailSuperieur()
    {
        return $this->mailSuperieur;
    }

    public function getPerimetre()
    {
        return $this->perimetre;
    }

    public function getVoitureAttribue()
    {
        return $this->voitureAttribue;
    }

    public function getDistanceDT()
    {
        return $this->distanceDT;
    }

    public function getCreateAt()
    {
        return $this->createAt;
    }

    public function getCreateBy()
    {
        return $this->createBy;
    }

    public function getUpdateAt()
    {
        return $this->updateAt;
    }

    public function getUpdateBy()
    {
        return $this->updateBy;
    }

    public function getDeletedAt()
    {
        return $this->deletedAt;
    }

    public function getSourceAgent()
    {
        return $this->sourceAgent;
    }

    public function setIdUser($idUser)
    {
        $this->idUser = $idUser;
    }

    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;
    }

    public function setCp($cp)
    {
        $this->cp = $cp;
    }

    public function setVille($ville)
    {
        $this->ville = $ville;
    }

    public function setTelephone($telephone)
    {
        $this->telephone = $telephone;
    }

    public function setGrade($grade)
    {
        $this->grade = $grade;
    }

    public function setMailSuperieur($mailSuperieur)
    {
        $this->mailSuperieur = $mailSuperieur;
    }

    public function setPerimetre($perimetre)
    {
        $this->perimetre = $perimetre;
    }

    public function setVoitureAttribue($voitureAttribue)
    {
        $this->voitureAttribue = $voitureAttribue;
    }

    public function setDistanceDT($distanceDT)
    {
        $this->distanceDT = $distanceDT;
    }

    public function setCreateAt($createAt)
    {
        $this->createAt = $createAt;
    }

    public function setCreateBy($createBy)
    {
        $this->createBy = $createBy;
    }

    public function setUpdateAt($updateAt)
    {
        $this->updateAt = $updateAt;
    }

    public function setUpdateBy($updateBy)
    {
        $this->updateBy = $updateBy;
    }

    public function setDeletedAt($deletedAt)
    {
        $this->deletedAt = $deletedAt;
    }

    public function setSourceAgent($sourceAgent)
    {
        $this->sourceAgent = $sourceAgent;
        $this->idUser = $this->sourceAgent->getAgeCodeDt();
    }

    public function __toString()
    {
        return $this->sourceAgent->getAgePrenomUsuel() . " " . $this->sourceAgent->getAgeNomUsuel();
    }

    public function getReservations()
    {
        return $this->reservations;
    }

    public function setReservations($reservations)
    {
        $this->reservations = $reservations;
    }

    public function getRegistres()
    {
        return $this->registres;
    }

    public function setRegistres($registres)
    {
        $this->registres = $registres;
    }

}

GestionReservationAuto/Form/RegistreForm.php
<?php

namespace DTC\Modules\GestionReservationAuto\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * Form
 *
 * @author wug870
 */
class RegistreForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        
        $builder->add('dateDebut', 'date', array(
            'label'=>'Date de début :',
            'widget'=>'single_text',
            'format' => 'dd/MM/yyyy',
        ));
        $builder->add('dateFin', 'date', array(
            'label'=>'Date de fin :',
            'widget'=>'single_text',
            'format' => 'dd/MM/yyyy',
        ));
        
    }

    public function getName() {
        return "Registre";
    }
}

GestionReservationAuto/Resources/views/registre/create.html.twig
{% extends "src/GestionReservationAuto/Resources/views/layout.html.twig" %}

{%set menu = 'registre' %}

{% block content %}
    <h3>Registre </h3>

    <table class="table table-hover" id="myTable">
        <thead>
        <th>Date création</th>
        <th>Date début</th>
        <th>Date fin</th>
        <th>Signature agent</th>
        <th>Signature supérieur</th>
        <th>Recevoir par mail</th>
        <th>Supprimer</th>
    </thead>
    {% for reg in lesReg %}
        <tr>
            <td>{{reg.dateCreation|date('d/m/Y')}}</td>
            <td>{{reg.dateDebut|date('d/m/Y ')}}</td>
            <td>{{reg.dateFin|date('d/m/Y ')}}</td>
            <td>{{reg.signatureAgent}}</td>
            <td>{{reg.signatureSuperieur}}</td>
            <td>{%if reg.signatureAgent != null and reg.signatureSuperieur != null%}<a href="{{ path('gestion-reservation-auto-registre-send', {'id': reg.idRegistre}) }}"><span class="glyphicon glyphicon-envelope"></span></a>{%endif%}</td>
            <td><a href="{{ path('gestion-reservation-auto-registre-delete', {'id': reg.idRegistre}) }}"><span class="glyphicon glyphicon-remove"></span></a></td>
        </tr>
    {%endfor%}
</table>
{{ form_start(form, { 'attr': { 'role': 'form' }, 'method': 'post' }) }}
{{ form_errors(form) }}
{% include 'src/GestionReservationAuto/Resources/views/registre/fragments/form.html.twig' %}


<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <input type="submit" name="submit" value="Valider" class="btn btn-default" />
        </div>
    </div>
</div>
{{ form_end(form) }}


{% endblock %}{# empty Twig template #}
{% block javascripts %}    
    {{parent()}}

    <script type="text/javascript">
        $(document).ready(function () {
            $("form input.date").datepicker({
                dateFormat: 'dd/mm/yy',
                firstDay: 1
            }).attr("readonly", "readonly");

            $('#JourneeForm_dateJourneeDate').datepicker({
                todayBtn: true,
                language: "fr",
                multidate: false,
                daysOfWeekDisabled: "0,6",
                autoclose: true,
                todayHighlight: true});
            $('#Registre_dateFin').datepicker({
                todayBtn: true,
                language: "fr",
                multidate: false,
                daysOfWeekDisabled: "0,6",
                autoclose: true,
                todayHighlight: true});
            
            var table = $('#myTable').DataTable({
                "language": {
                    "url": "{{ baseRoutePrefix }}/i18n/datatables.french.json"
                },
                "order": [
                    [1, "desc"]
                ]
            });

            $(document).on("keyup", ".dataTables_filter input[type=search]", function () {
                var body = $(table.table().body());

                var txtSearchOriginal = this.value;
                var txtSearchRewrite = jQuery.fn.DataTable.ext.type.search.string(txtSearchOriginal);

                table.search(
                        txtSearchRewrite
                        ).draw();

                body.highlight([txtSearchOriginal, txtSearchRewrite]);
            });
        });
    </script>
{% endblock %}

GestionReservationAuto/Resources/views/registre/mailRegistre.html.twig
{% block content %}
        <style type='text/css'>
            #regles{background-color:silver;}
            #regles p{margin-left: 10px;}
            table th td{border: 1px solid black;border-collapse: collapse;}
	</style>
	<h2 align='center'>Registre des réservations</h2><br/>
        <b>Agent :</b> {{reg.user.nom}} {{reg.user.prenom}}<br/><br/>
        <b>Identifiant :</b> {{reg.user.idUser}}<br/><br/>
        <b>Service :</b> {{reg.user.sourceAgent.sourceOrgaAffectectation.regCode}} {{reg.user.sourceAgent.sourceOrgaAffectectation.entLibelle}}<br/><br/>
        <div class="clearfix"></div>
        <table class="table table-hover" id="myTable">
            <thead>
                <th style="border: solid 1px black;boder-collapse: collapse;">Voiture</th>
                <th style="border: solid 1px black;boder-collapse: collapse;">Date début</th>
                <th style="border: solid 1px black;boder-collapse: collapse;">Date fin</th>
                <th style="border: solid 1px black;boder-collapse: collapse;">Date création</th>
                <th style="border: solid 1px black;boder-collapse: collapse;">Destination</th>
                <th style="border: solid 1px black;boder-collapse: collapse;">Distance (km)</th>
                <th style="border: solid 1px black;boder-collapse: collapse;">Motif</th>
            </thead>
            {% for res in lesRes %}
                <tr>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.voiture.vehicule.vehImmat}}</td>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.dateDebut|date('d/m/Y ')}}</td>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.dateFin|date('d/m/Y ')}}</td>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.dateCreation|date('d/m/Y')}}</td>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.destination}}</td>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.distance}}</td>
                    <td style="border: solid 1px black;boder-collapse: collapse;">{{res.motif}}</td>
                </tr>
            {%endfor%}
        </table>
        <b>Code du registe : </b>{{reg.idRegistre}}<br/><br/>
        <b>Signature agent : </b>{{reg.signatureAgent}}<br/><br/>
        <b>Signature supérieur :</b>{{reg.signatureSuperieur}}<br/><br/>
        
	
        
{% endblock %}

GestionReservationAuto/Resources/views/registre/preview.html.twig
{% extends "src/GestionReservationAuto/Resources/views/layout.html.twig" %}


{%set menu = 'registre' %}

{% block content %}
    <h3>Registre du {{reg.dateDebut|date('d/m/Y')}} au {{reg.dateFin|date('d/m/Y')}}</h3>
    <div class="row">
        <div class="col-md-12">
            <b>Agent :</b> {{reg.user.nom}} {{reg.user.prenom}}<br/><br/>
            <b>Identifiant :</b> {{reg.user.idUser}}<br/><br/>
{#            <b>Service :</b> {{reg.user.service.regate}} {{reg.user.service.libelle}}<br/><br/>#}
            <div class="clearfix"></div>
            <table class="table table-hover" id="myTable">
                <thead>
                    <th>Voiture</th>
                    <th>Date début</th>
                    <th>Date fin</th>
                    <th>Date création</th>
                    <th>Destination</th>
                    <th>Distance (km)</th>
                    <th>Motif</th>
                </thead>
                {% for res in lesRes %}
                     <tr>
                        <td>{{res.voiture.vehicule.vehImmat}}</td>
                        <td>{{res.dateDebut|date('d/m/Y H')}}h</td>
                        <td>{{res.dateFin|date('d/m/Y H')}}h</td>
                        <td>{{res.dateCreation|date('d/m/Y')}}</td>
                        <td>{{res.destination}}</td>
                        <td>{{res.distance}}</td>
                        <td>{{res.motif}}</td>
                    </tr>
                {%endfor%}
            </table>
            <div class="col-md-2"><a href="{{ path('gestion-reservation-auto-registre-signature-agent', {'id': reg.idRegistre}) }}"class="btn btn-success">Signer</a></div>
            <div class="col-md-2"><a href="{{ path('gestion-reservation-auto-registre-delete', {'id': reg.idRegistre}) }}"class="btn btn-danger">Annuler registre</a></div>
        </div>
    </div>
{% endblock %}

GestionReservationAuto/Resources/views/registre/readByService.html.twig
{% extends "src/GestionReservationAuto/Resources/views/layout.html.twig" %}

{%set menu = 'gestionRegistre' %}

{% block content %}
    <h3>Liste des registres du service</h3>
    <p>Cette icône <span class="glyphicon glyphicon-envelope"></span> vous envoie un mail contenant le registre et son contenu.</p>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-hover" id="myTable">
                <thead>
                <th>Utilisateur</th>
                <th>Date création</th>
                <th>Date début</th>
                <th>Date fin</th>
                <th>Signature Agent</th>
                <th>Signature supérieur</th>
                <th>Recevoir par email</th>
                </thead>
                {% for reg in lesRegistre %}
                    <tr>
                        <td>{{reg.user.nom}} {{reg.user.prenom}}</td>
                        <td>{{reg.dateCreation|date('d/m/Y')}}</td>
                        <td>{{reg.dateDebut|date('d/m/Y H')}}h</td>
                        <td>{{reg.dateFin|date('d/m/Y H')}}h</td>
                        <td>{{reg.signatureAgent}}</td>
                        {% if reg.dateDebut|date('d-m-Y') != reg.dateFin|date('d-m-Y')%}
                            {% if reg.signatureSuperieur != null %}
                                <td>{{reg.signatureSuperieur}}</td>
                            {%else%}
                                <td> <a href="{{ path('gestion-reservation-auto-registre-signature-superieur', {'id': reg.idRegistre}) }}"class="btn btn-xs btn-warning">Signer</a></td>
                            {%endif%}
                        {%else%}
                            <td></td>
                        {%endif%}
                        <td>{%if reg.signatureAgent != null and reg.signatureSuperieur != null%}<a href="{{ path('gestion-reservation-auto-registre-send-superieur', {'id': reg.idRegistre}) }}"><span class="glyphicon glyphicon-envelope"></span></a>{%endif%}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}{# empty Twig template #}
{% block javascripts %}
    {{parent()}}
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#myTable').DataTable({
                "language": {
                    "url": "{{ baseRoutePrefix }}/i18n/datatables.french.json"
                },
                "order": [[1, "desc"]]
            });

            $(document).on("keyup", ".dataTables_filter input[type=search]", function () {
                var body = $(table.table().body());

                var txtSearchOriginal = this.value;
                var txtSearchRewrite = jQuery.fn.DataTable.ext.type.search.string(txtSearchOriginal);

                table.search(
                        txtSearchRewrite
                        ).draw();

                body.highlight([txtSearchOriginal, txtSearchRewrite]);
            });
        });
    </script>
{%endblock%}